name: pills
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite: ^2.4.0
  flutter_local_notifications: ^17.2.3
  android_alarm_manager_plus: ^4.0.4
  permission_handler: ^11.3.1
  date_picker_timeline: ^1.2.6
  mailer: ^6.2.0
  flutter_svg: ^2.0.10+1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
